#!/usr/bin/env bash

for i in 1.1.12 1.1.13 1.1.14 1.1.15 1.1.16 1.2.0 1.2.1 1.2.2 1.2.3 1.2.4 1.2.5 1.3.0 1.3.1 1.3.2 1.3.3 1.3.4 1.3.5 1.3.6 1.3.7 1.3.8 1.3.9 1.4.0 1.4.1 1.4.2 1.4.3 1.5.0 1.5.1 1.6.0 1.7.0 1.7.1 1.8.0 1.8.1 1.8.2 1.8.3 1.8.4 1.9.0 1.9.1 1.9.2 1.9.3; do
    git rm -fr parse/libs
    git checkout $i parse/libs
    sed -i "s/VERSION_NAME=.*/VERSION_NAME=${i}/" parse/gradle.properties
    version_code=`echo $i | sed -e 's/\.\([0-9]\)$/.0\1/' -e 's/\.//g'`
    sed -i "s/VERSION_CODE=.*/VERSION_CODE=${version_code}/" parse/gradle.properties
    ./gradlew clean uploadArchives
    git add parse/libs
    git add parse/gradle.properties
    git commit -m "$i"
done
